version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.1
    - 7.13.15
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.13.15
    - 7.13.9
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.8
  - dependency-name: husky
    versions:
    - 5.0.9
  - dependency-name: "@preconstruct/cli"
    versions:
    - 2.0.2
  - dependency-name: "@changesets/cli"
    versions:
    - 2.14.0
  registries:
  - npm-registry-registry-npmjs-org
  - npm-registry-npm-pkg-github-com
