name: Release

on:
  push:
    branches:
      - sandbox

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
          registry-url: https://npm.pkg.github.com
          scope: '@wpmedia'

      - name: Install Dependencies
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create new branch in order to persist changesets through to prod branch
      - name: Create snapshot sandbox branch
        run: git checkout -b sandbox-tag

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Create snaphost release for sandbox
        run: npm run release:snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @beta release to npm
        # Calls changeset publish --tag [beta|stable]
        run: npm run release:sandbox
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
